#!/usr/bin/env bash
# probe_lib10.sh — Phase 10 safety envelope for the ONE window in this phase
# where com.ohama.litellm's pid and the live config's sha256 are SUPPOSED to
# change. Phase 9's probe_lib.sh cannot be used unmodified for the top-level
# gate here: its postflight() fails the run the moment ANY of the three
# tracked pids differs, or the moment litellm-config.yaml's hash differs --
# and in this plan both are the intended outcome of Restart A/B.
#
# This file does NOT fork phase-09/probe_lib.sh. It SOURCES it, purely for
# flake_window() and record_verdict() (the four-state anti-flake rule is
# reused verbatim, unmodified, because nothing about that rule changes here)
# -- and adds only what differs: preflight10/postflight10, which understand
# a legitimate litellm restart and a legitimate live-config-hash change,
# while still treating a flashnext/role-shim pid change or a providers.json
# write as an unconditional, always-hard failure.
#
# bash 3.2 compatible (no declare -A, no ${var^^}) -- this machine's default
# /bin/bash.
set -uo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# ---- Phase 10 paths (distinct from phase-09/probe_lib.sh's paths) ----------
LIVE_CFG="/Users/ohama/agent-stack/litellm/config.yaml"                       # what litellm actually loads
MIRROR_CFG="$HOME/local-llm-settings/config/litellm-config.yaml"              # generated by sync.sh; NOT loaded by litellm
PROVIDERS="$HOME/.cline/data/settings/providers.json"
FLASHNEXT_LOG="$HOME/llm-system/services/logs/flashnext.err"
SVC_RE='com\.ohama\.(flashnext|role-shim|litellm)'
VERIFY_CONFIG_SH="$HERE/../phase-01/config/verify_config.sh"

# ---- reuse phase-09/probe_lib.sh verbatim for flake_window/record_verdict --
# Sourcing (not forking) also brings in phase-09's own preflight()/
# postflight() function names, but this file never calls those -- only its
# own preflight10()/postflight10() below are used by this phase's plans.
# shellcheck source=/dev/null
source "$HERE/../phase-09/probe_lib.sh"

# ---- new_run_dir10 <tag> ----------------------------------------------------
# Like phase-09's new_run_dir, but rooted at phase-10/results/.
new_run_dir10() {
  local tag="$1"
  local dir="$HERE/results/$(date -u +%Y%m%dT%H%M%SZ)-${tag}"
  mkdir -p "$dir"
  echo "$dir"
}

# ---- preflight10 <run_dir> ---------------------------------------------------
# Snapshots the three com.ohama.* pids (fails if fewer than 3 found), sha256
# of LIVE_CFG/MIRROR_CFG/PROVIDERS, the flashnext.err line count as
# LOG_WATERMARK (exported, for flake_window), the idleness poll, and the
# advisory cline-process check.
preflight10() {
  local run_dir="$1"
  : > "$run_dir/preflight.txt"
  echo "=== preflight10 $(date -u +%Y-%m-%dT%H:%M:%SZ) ===" >> "$run_dir/preflight.txt"

  launchctl list | grep -E "$SVC_RE" | awk '{print $3" "$1}' | sort > "$run_dir/pids-before.txt"
  local n_lines
  n_lines=$(wc -l < "$run_dir/pids-before.txt" | tr -d ' ')
  if [ "$n_lines" -lt 3 ]; then
    echo "FATAL: expected 3 services (flashnext, role-shim, litellm), found $n_lines" | tee -a "$run_dir/preflight.txt" >&2
    return 1
  fi
  echo "--- pids-before.txt ---" >> "$run_dir/preflight.txt"
  cat "$run_dir/pids-before.txt" >> "$run_dir/preflight.txt"

  shasum -a 256 "$LIVE_CFG" "$MIRROR_CFG" "$PROVIDERS" > "$run_dir/hashes-before.txt"
  echo "--- hashes-before.txt (live, mirror, providers.json) ---" >> "$run_dir/preflight.txt"
  cat "$run_dir/hashes-before.txt" >> "$run_dir/preflight.txt"

  LOG_WATERMARK=$(wc -l < "$FLASHNEXT_LOG" | tr -d ' ')
  export LOG_WATERMARK
  echo "LOG_WATERMARK=$LOG_WATERMARK" >> "$run_dir/preflight.txt"

  echo "--- tail -2 $FLASHNEXT_LOG ---" >> "$run_dir/preflight.txt"
  tail -2 "$FLASHNEXT_LOG" >> "$run_dir/preflight.txt" 2>&1 || true

  local attempt=0
  local idle_ok=0
  local last_inflight_line=""
  while [ "$attempt" -lt 10 ]; do
    last_inflight_line=$(grep 'in_flight=' "$FLASHNEXT_LOG" | tail -1 || true)
    case "$last_inflight_line" in
      *"in_flight=0"*)
        idle_ok=1
        break
        ;;
    esac
    attempt=$((attempt + 1))
    sleep 3
  done
  if [ "$idle_ok" -ne 1 ]; then
    echo "FATAL: model not idle after 10 retries (last in_flight line: $last_inflight_line)" | tee -a "$run_dir/preflight.txt" >&2
    return 1
  fi
  echo "idle check: OK -- $last_inflight_line" >> "$run_dir/preflight.txt"

  echo "--- advisory (hint only, NOT a hard gate): running cline processes ---" >> "$run_dir/preflight.txt"
  pgrep -fl 'bin/\.cline|bin/cline' >> "$run_dir/preflight.txt" 2>/dev/null || echo "(none found)" >> "$run_dir/preflight.txt"

  return 0
}

# ---- postflight10 <run_dir> <expected_live_cfg_sha> <litellm_restart_expected:0|1> --
postflight10() {
  local run_dir="$1"
  local expected_live_sha="$2"
  local restart_expected="$3"
  local ok=1
  : > "$run_dir/postflight.txt"
  echo "=== postflight10 $(date -u +%Y-%m-%dT%H:%M:%SZ) (expected_live_sha=$expected_live_sha restart_expected=$restart_expected) ===" >> "$run_dir/postflight.txt"

  launchctl list | grep -E "$SVC_RE" | awk '{print $3" "$1}' | sort > "$run_dir/pids-after.txt"

  # ---- flashnext + role-shim: ALWAYS hard, in every plan of this phase ----
  local before_flashnext after_flashnext before_roleshim after_roleshim
  before_flashnext=$(awk '$1=="com.ohama.flashnext"{print $2}' "$run_dir/pids-before.txt")
  after_flashnext=$(awk '$1=="com.ohama.flashnext"{print $2}' "$run_dir/pids-after.txt")
  before_roleshim=$(awk '$1=="com.ohama.role-shim"{print $2}' "$run_dir/pids-before.txt")
  after_roleshim=$(awk '$1=="com.ohama.role-shim"{print $2}' "$run_dir/pids-after.txt")

  if [ "$before_flashnext" = "$after_flashnext" ] && [ -n "$before_flashnext" ]; then
    echo "OK: com.ohama.flashnext pid unchanged ($before_flashnext)" >> "$run_dir/postflight.txt"
  else
    echo "FAIL: com.ohama.flashnext pid changed (before=$before_flashnext after=$after_flashnext) -- MUST NEVER restart" >> "$run_dir/postflight.txt"
    ok=0
  fi

  if [ "$before_roleshim" = "$after_roleshim" ] && [ -n "$before_roleshim" ]; then
    echo "OK: com.ohama.role-shim pid unchanged ($before_roleshim)" >> "$run_dir/postflight.txt"
  else
    echo "FAIL: com.ohama.role-shim pid changed (before=$before_roleshim after=$after_roleshim) -- MUST NEVER restart" >> "$run_dir/postflight.txt"
    ok=0
  fi

  # ---- litellm pid: must change iff a restart was expected ----
  local before_litellm after_litellm
  before_litellm=$(awk '$1=="com.ohama.litellm"{print $2}' "$run_dir/pids-before.txt")
  after_litellm=$(awk '$1=="com.ohama.litellm"{print $2}' "$run_dir/pids-after.txt")
  echo "com.ohama.litellm pid: before=$before_litellm after=$after_litellm" >> "$run_dir/postflight.txt"
  if [ "$restart_expected" = "1" ]; then
    if [ -n "$before_litellm" ] && [ -n "$after_litellm" ] && [ "$before_litellm" != "$after_litellm" ]; then
      echo "OK: com.ohama.litellm pid changed as expected (restart_expected=1)" >> "$run_dir/postflight.txt"
    else
      echo "FAIL: com.ohama.litellm pid did NOT change though a restart was expected (restart_expected=1) -- bootout/bootstrap likely did not actually happen" >> "$run_dir/postflight.txt"
      ok=0
    fi
  else
    if [ "$before_litellm" = "$after_litellm" ] && [ -n "$before_litellm" ]; then
      echo "OK: com.ohama.litellm pid unchanged as expected (restart_expected=0)" >> "$run_dir/postflight.txt"
    else
      echo "FAIL: com.ohama.litellm pid changed though NO restart was expected (restart_expected=0)" >> "$run_dir/postflight.txt"
      ok=0
    fi
  fi

  # ---- providers.json: ALWAYS hard, in every plan of this phase ----
  local providers_before providers_after
  providers_before=$(awk -v p="$PROVIDERS" '$2==p{print $1}' "$run_dir/hashes-before.txt")
  shasum -a 256 "$LIVE_CFG" "$MIRROR_CFG" "$PROVIDERS" > "$run_dir/hashes-after.txt"
  providers_after=$(awk -v p="$PROVIDERS" '$2==p{print $1}' "$run_dir/hashes-after.txt")
  if [ "$providers_before" = "$providers_after" ] && [ -n "$providers_before" ]; then
    echo "OK: providers.json sha256 unchanged ($providers_before)" >> "$run_dir/postflight.txt"
  else
    echo "FAIL: providers.json sha256 changed (before=$providers_before after=$providers_after) -- MUST NEVER be written in this phase" >> "$run_dir/postflight.txt"
    ok=0
  fi

  # ---- LIVE_CFG: must equal the caller's expected hash ----
  local live_after
  live_after=$(awk -v p="$LIVE_CFG" '$2==p{print $1}' "$run_dir/hashes-after.txt")
  if [ "$live_after" = "$expected_live_sha" ]; then
    echo "OK: live config sha256 equals expected ($live_after)" >> "$run_dir/postflight.txt"
  else
    echo "FAIL: live config sha256 ($live_after) != expected ($expected_live_sha)" >> "$run_dir/postflight.txt"
    ok=0
  fi

  # ---- MIRROR_CFG: recorded, never enforced -- it legitimately diverges ----
  # from LIVE_CFG once this plan installs a new live config (mirror is not
  # regenerated until plan 10-06's sync.sh runs). The useful comparison is
  # MIRROR vs the CURRENT LIVE_CFG, not mirror-before vs mirror-after -- the
  # latter is always trivially "unchanged" since nothing in this phase ever
  # writes to the mirror, and would silently mislabel a real divergence (the
  # mirror still holding the OLD bytes while live now holds the candidate)
  # as "in-sync" -- caught during this plan's own dry run before being
  # trusted; see 10-03-SUMMARY.md Deviations.
  local mirror_after
  mirror_after=$(awk -v p="$MIRROR_CFG" '$2==p{print $1}' "$run_dir/hashes-after.txt")
  if [ "$mirror_after" = "$live_after" ]; then
    echo "MIRROR: in-sync (mirror == live, both: $mirror_after)" >> "$run_dir/postflight.txt"
  else
    echo "MIRROR: diverged-as-expected (mirror=$mirror_after live=$live_after) -- expected until plan 10-06's sync.sh runs" >> "$run_dir/postflight.txt"
  fi

  # ---- independent, non-fatal check ----
  echo "--- independent check: verify_config.sh (non-fatal, always recorded) ---" >> "$run_dir/postflight.txt"
  if [ -x "$VERIFY_CONFIG_SH" ] || [ -f "$VERIFY_CONFIG_SH" ]; then
    bash "$VERIFY_CONFIG_SH" >> "$run_dir/postflight.txt" 2>&1 || true
  else
    echo "(verify_config.sh not found at $VERIFY_CONFIG_SH -- skipped)" >> "$run_dir/postflight.txt"
  fi

  # ---- no self-repair -- same rule as Phase 9 ----
  if [ "$ok" -ne 1 ]; then
    echo "postflight10: one or more HARD checks FAILED -- no self-repair performed. See above." >> "$run_dir/postflight.txt"
    return 1
  fi
  return 0
}
